services:
  interface:
    image: joltdesign/db-find-replace
    profiles:
      - ""
      - test
    build:
      context: .
      dockerfile: Containerfile
    environment:
      TEST_DB_HOST: test_db
      TEST_DB_USER: root
      TEST_DB_PASS: dbpass
    ports:
      - 8080:80
    volumes:
      - ./src/:/var/www/html/:delegated
    restart: unless-stopped

  db:
    image: mariadb:11
    restart: unless-stopped
    ports:
      - 3306
    volumes:
      - ./db-seed-input/:/docker-entrypoint-initdb.d/:ro
      # Data persistence is disabled by default - uncomment this and the entry in volumes: at the bottom of the file if you need it
      # - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: joltdbpass

  test_db:
    image: mariadb:11
    profiles: [test]
    ports:
      - 3306
    environment:
      MARIADB_DATABASE: srdbtest
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: dbpass

  adminer:
    image: joltdesign/adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: database
      MYSQL_USER: root
      MYSQL_PASSWORD: joltdbpass

volumes:
  db_data:
